// Generates src/components/ui/icon-names.ts from the files in public/icons.
// The name list is the set of icons the site may use: <Icon name="..."> only
// accepts these names, so a typo fails to compile. Each entry is a short hash
// of the file, used as ?v= in the URL so a changed icon gets a new URL (the
// files are cached for a year). Runs before `dev` and `build`.
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";

const DIR = "public/icons";
const OUT = "src/components/ui/icon-names.ts";

const names = readdirSync(DIR).filter((f) => f.endsWith(".svg")).map((f) => f.slice(0, -4)).sort();
const entries = names.map((name) => {
  const hash = createHash("sha1").update(readFileSync(`${DIR}/${name}.svg`)).digest("hex").slice(0, 8);
  return `  "${name}": "${hash}",`;
});

const source = `// Generated by scripts/icons/build.mjs from public/icons. Do not edit by hand.
export const ICON_VERSION = {
${entries.join("\n")}
} as const;

export type IconName = keyof typeof ICON_VERSION;
`;

let previous = "";
try { previous = readFileSync(OUT, "utf8"); } catch {}
if (previous !== source) writeFileSync(OUT, source);
console.log(`icons: ${names.length} (${OUT})`);
